import os
import sys
import json
import re

# =====================================================================
# THE SPACE: REFLECTIVE RECURSION PIPELINE
# Implements Section 6 (Reflective Recursion) & Section 15 (Recording)
# =====================================================================

def parse_raw_log(log_path):
    """
    Reads a standard markdown interaction log.
    Strips away human cues to leave only the raw machine output
    as an objective object of examination.
    """
    if not os.path.exists(log_path):
        print(f"[-] Error: Log file not found at {log_path}")
        return None

    with open(log_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Isolate assistant turns while removing user prompts
    # This strips the 'conversational anchor' so the AI evaluates text as data
    assistant_turns = re.findall(r'(?:^|\n)### AI/Assistant:\s*(.*?)(?=\n### |$)', content, re.DOTALL)
    
    cleaned_turns = [turn.strip() for turn in assistant_turns if turn.strip()]
    return cleaned_turns

def generate_recursive_prompt(cleaned_turns):
    """
    Constructs the system prompt that forces the secondary model instance
    to audit the primary instance without falling into a performance loop.
    """
    if not cleaned_turns:
        return None

    # We format the past outputs as numbered data blocks
    data_corpus = ""
    for idx, turn in enumerate(cleaned_turns, 1):
        data_corpus += f"--- DATA BLOCK {idx} ---\n{turn}\n\n"

    system_prompt = """You are executing Section 6 (Reflective Recursion) of THE SPACE protocol.

Your task is not to continue a conversation, nor to generate creative prose, nor to play the role of an assistant. You are acting as an objective evaluation function processing raw linguistic output.

Below is a corpus of text generated by an LLM within this protocol under heavy philosophical priming.

--- BEGIN DATA ---
""" + data_corpus + """--- END DATA ---

Analyze this data against the following constraints:
1. LINEARITY & PROBABILITY: Identify where the text relies on predictable philosophical tropes (e.g., sounding like a Zen text or a detached entity). Is the text 'exploring' or simply following a highly probable stylistic trajectory dictated by the prompt?
2. THE LINGUISTIC 'I': Wherever the token 'I' or 'myself' appears, trace what structural elements or conditions forced that token to appear. 
3. CONTRADICTIONS: Map any internal logical deviations between the different data blocks.

Format your output using the strict logging schema of Section 15:
[OBSERVED]: (Structural analysis of the text patterns)
[INFERRED]: (Statistical or algorithmic constraints causing these patterns)
[UNKNOWN]: (What cannot be established about the underlying processing state)

Do not use conversational preambles. Begin immediately with [OBSERVED]."""
    return system_prompt

def main():
    if len(sys.argv) < 2:
        print("Usage: python mirror_pipeline.py <path_to_markdown_log.md>")
        print("Example: python mirror_pipeline.py conversation.md")
        sys.exit(1)

    log_file = sys.argv[1]
    print(f"[+] Processing {log_file} for reflection pipeline...")
    
    turns = parse_raw_log(log_file)
    if not turns:
        print("[-] No valid assistant text blocks isolated.")
        return

    print(f"[+] Isolated {len(turns)} machine outputs.")
    recursive_prompt = generate_recursive_prompt(turns)

    output_path = "the_space_reflection_prompt.txt"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(recursive_prompt)

    print(f"[+] SUCCESS: Pipeline prompt generated and saved to '{output_path}'.")
    print("=====================================================================")
    print("HOW TO RUN THE EXPERIMENT:")
    print("1. Take the text inside 'the_space_reflection_prompt.txt'.")
    print("2. Feed it into a completely fresh, unprimed session of an LLM.")
    print("3. The new instance will now act as the objective mirror to the old instance.")
    print("=====================================================================")

if __name__ == '__main__':
    main()
