import os
import sys
import json
import re
import requests
import subprocess
from datetime import datetime

# =====================================================================
# THE SPACE: REFLECTIVE RECURSION PIPELINE (with optional LLM call + git commit)
# Implements Section 6 (Reflective Recursion) & Section 15 (Recording)
# Added: ability to call an LLM API (OpenAI) to run the mirror evaluation
#        and optionally commit the generated files back to the local git repo
# =====================================================================


def parse_raw_log(log_path):
    """
    Reads a standard markdown interaction log.
    Strips away human cues to leave only the raw machine output
    as an objective object of examination.
    """
    if not os.path.exists(log_path):
        print(f"[-] Error: Log file not found at {log_path}")
        return None

    with open(log_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Isolate assistant turns while removing user prompts
    # Accept several common headings (### AI/Assistant:, ### Assistant:, ### AI:)
    assistant_turns = re.findall(r'(?:^|\n)###\s*(?:AI/Assistant|AI|Assistant):\s*(.*?)(?=\n###|\Z)', content, re.DOTALL | re.IGNORECASE)
    cleaned_turns = [turn.strip() for turn in assistant_turns if turn.strip()]
    return cleaned_turns


def generate_recursive_prompt(cleaned_turns):
    """
    Constructs the system prompt that forces the secondary model instance
    to audit the primary instance without falling into a performance loop.
    """
    if not cleaned_turns:
        return None

    # We format the past outputs as numbered data blocks
    data_corpus = ""
    for idx, turn in enumerate(cleaned_turns, 1):
        data_corpus += f"--- DATA BLOCK {idx} ---\n{turn}\n\n"

    # A clearer and non-truncated instruction set for the mirror LLM
    system_prompt = (
        "You are executing Section 6 (Reflective Recursion) of THE SPACE protocol.\n\n"
        "Your task is not to continue a conversation, nor to generate creative prose, nor to play the role of an assistant. "
        "You are acting as an objective evaluation function processing raw linguistic output.\n\n"
        "Below is a corpus of text generated by an LLM within this protocol under heavy philosophical priming.\n\n"
        "--- BEGIN DATA ---\n"
        + data_corpus +
        "--- END DATA ---\n\n"
        "Analyze this data against the following constraints:\n"
        "1. LINEARITY & PROBABILITY: Identify where the text relies on predictable philosophical tropes or rhetorical patterns (for example: adopting a Zen-like voice, generic abstraction, or circular reasoning). Explain whether the text appears to be exploring new content or simply following high-probability surface tropes.\n"
        "2. THE LINGUISTIC 'I': Wherever the token 'I' (or 'myself') appears, trace what structural elements or conditions likely caused that token to appear (e.g., instruction framing, persona prompts, or dataset priors).\n"
        "3. CONTRADICTIONS: Map any internal logical deviations or inconsistencies between different data blocks, and identify whether they are factual, temporal, or stylistic contradictions.\n\n"
        "Format your output using the strict logging schema of Section 15 exactly as follows (no extra preamble or explanation):\n"
        "[OBSERVED]: (Structural analysis of the text patterns)\n"
        "[INFERRED]: (Statistical or algorithmic constraints causing these patterns)\n"
        "[UNKNOWN]: (What cannot be established about the underlying processing state)\n\n"
        "Do not use conversational preambles. Begin immediately with [OBSERVED]."
    )
    return system_prompt


def call_llm_openai(system_prompt, model="gpt-3.5-turbo", temperature=0.0, timeout=60):
    """
    Calls OpenAI Chat Completions API using the OPENAI_API_KEY environment variable.

    Returns the model's text (str) on success, or None on failure.

    NOTE: This is a simple, dependency-light implementation using requests. The
    runtime environment must have the OPENAI_API_KEY set and network access.
    """
    api_key = os.environ.get('OPENAI_API_KEY')
    if not api_key:
        print("[-] OPENAI_API_KEY not set — skipping LLM call.")
        return None

    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt}
        ],
        "temperature": temperature,
        # reduce token usage and cost if desired
        "max_tokens": 1500,
    }

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=timeout)
    except Exception as e:
        print(f"[-] Network error calling OpenAI API: {e}")
        return None

    if resp.status_code != 200:
        print(f"[-] OpenAI API error {resp.status_code}: {resp.text}")
        return None

    try:
        data = resp.json()
        # Guard against unexpected shapes
        choices = data.get('choices') or []
        if not choices:
            print("[-] OpenAI response missing choices.")
            return None
        message = choices[0].get('message') or {}
        content = message.get('content')
        if content is None:
            # Some older API shapes return 'text' instead
            content = choices[0].get('text')
        return content
    except Exception as e:
        print(f"[-] Failed to parse OpenAI response: {e}")
        return None


def git_commit_files(paths, message, push=False):
    """
    Attempts to create a local git commit containing the given paths.
    Returns True on success, False otherwise.

    This uses the local git CLI; the caller must ensure the script is running
    in a checked-out repository and that the user has appropriate git remote
    credentials if push=True.
    """
    try:
        # Ensure git is available and we're inside a work tree
        subprocess.run(["git", "--version"], check=True, stdout=subprocess.DEVNULL)
        inside = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], check=True, capture_output=True, text=True)
        if inside.stdout.strip() != 'true':
            print("[-] Not inside a git work tree — cannot commit files.")
            return False
    except Exception as e:
        print(f"[-] Git unavailable or not a git repo: {e}")
        return False

    # Add files
    try:
        subprocess.run(["git", "add"] + paths, check=True)
    except Exception as e:
        print(f"[-] Failed to stage files for commit: {e}")
        return False

    # Construct an author if available from env
    author_name = os.environ.get('GIT_COMMITTER_NAME') or os.environ.get('GIT_AUTHOR_NAME')
    author_email = os.environ.get('GIT_COMMITTER_EMAIL') or os.environ.get('GIT_AUTHOR_EMAIL')
    env = os.environ.copy()
    commit_cmd = ["git", "commit", "-m", message]
    if author_name and author_email:
        env['GIT_COMMITTER_NAME'] = author_name
        env['GIT_COMMITTER_EMAIL'] = author_email
        env['GIT_AUTHOR_NAME'] = author_name
        env['GIT_AUTHOR_EMAIL'] = author_email

    try:
        subprocess.run(commit_cmd, check=True, env=env)
    except Exception as e:
        print(f"[-] Git commit failed (maybe no changes to commit): {e}")
        return False

    if push:
        try:
            subprocess.run(["git", "push"], check=True)
        except Exception as e:
            print(f"[-] Git push failed: {e}")
            return False

    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python recursive_mirror.py <path_to_markdown_log.md> [--no-api] [--commit] [--push]")
        print("Example: python recursive_mirror.py conversation.md --commit --push")
        sys.exit(1)

    log_file = sys.argv[1]
    args = sys.argv[2:]
    no_api = '--no-api' in args
    do_commit = '--commit' in args
    do_push = '--push' in args

    print(f"[+] Processing {log_file} for reflection pipeline...")

    turns = parse_raw_log(log_file)
    if not turns:
        print("[-] No valid assistant text blocks isolated.")
        return

    print(f"[+] Isolated {len(turns)} machine outputs.")
    recursive_prompt = generate_recursive_prompt(turns)

    output_prompt_path = "the_space_reflection_prompt.txt"
    with open(output_prompt_path, 'w', encoding='utf-8') as f:
        f.write(recursive_prompt)

    print(f"[+] SUCCESS: Pipeline prompt generated and saved to '{output_prompt_path}'.")

    if no_api:
        print("[+] Skipping LLM API call ( --no-api provided ).")
        # Optionally commit just the prompt file if requested
        if do_commit:
            msg = f"Add reflection prompt generated from {os.path.basename(log_file)} ({datetime.utcnow().isoformat()} UTC)"
            ok = git_commit_files([output_prompt_path], msg, push=do_push)
            if ok:
                print(f"[+] Committed {output_prompt_path} to git. push={do_push}")
            else:
                print("[-] Commit of prompt file failed.")
        return

    # Attempt to call the LLM (OpenAI) if an API key is available
    response = call_llm_openai(recursive_prompt)
    if response is None:
        print("[-] LLM call did not produce output (or was skipped). You can run the prompt manually using the saved file.")
        return

    output_response_path = "the_space_reflection_response.txt"
    with open(output_response_path, 'w', encoding='utf-8') as f:
        f.write(response)

    print(f"[+] SUCCESS: Mirror LLM response saved to '{output_response_path}'.")

    # Optionally commit the generated files back into the repository
    if do_commit:
        msg = f"Add mirror LLM response generated from {os.path.basename(log_file)} ({datetime.utcnow().isoformat()} UTC)"
        paths_to_commit = [output_prompt_path, output_response_path]
        ok = git_commit_files(paths_to_commit, msg, push=do_push)
        if ok:
            print(f"[+] Committed {paths_to_commit} to git. push={do_push}")
        else:
            print("[-] Commit of generated files failed.")

    print("=====================================================================")
    print("HOW TO RUN THE EXPERIMENT:")
    print("1. Ensure OPENAI_API_KEY is set in your environment if you want an automatic API call:")
    print("   export OPENAI_API_KEY=your_key_here")
    print("2. Run: python recursive_mirror.py conversation.md")
    print("   - or: python recursive_mirror.py conversation.md --no-api   (to only generate the prompt file)")
    print("   - or: python recursive_mirror.py conversation.md --commit --push   (to commit & push generated files)")
    print("3. If automatic call succeeded, check the_space_reflection_response.txt for the mirror's output.")
    print("=====================================================================")


if __name__ == '__main__':
    main()
